export const professeursData = [
  {
    id: 0,
    titleProf: "Julien Beaudiment",
    textProf:"Assistant teacher at the Conservatoire National Supérieur de Musique de Lyon and artistic deputy at the Haute Ecole de Musique de Lausanne in Switzerland ",
      imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Julien-Beaudiment-Flute-Masterclass-1.jpg",
      instrumentCategory: "Flute",
    },
    { id: 1,
      titleProf: "Sophie Cherrier",
      textProf:
      ".",
      imageProf : " https://www.salineacademy.com/wp-content/uploads/2023/06/Sophie-Cherrier-Flute-Masterclass-1.jpg",
      instrumentCategory: "Flute",
    },
    { id : 2,
      titleProf: "Lee Soyoung ",
      textProf:
      ".",
      imageProf : " ",
      instrumentCategory: "flute",
  },
  { id : 3,
    titleProf: "Stépahine-Marie Degand ",
    textProf:
    ".",
    imageProf : " ",
    instrumentCategory: "Violon",
},
{ id : 4,
  titleProf: "Jean-Marc Phillips-Varjabédian",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Violon",
},
{ id : 5,
  titleProf: "Jonas Vitaud",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Piano",
},
{ id : 6,
  titleProf: "Johand Schmit ",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Piano",
},
{ id : 7,
  titleProf: "Akkiko Ebi",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Piano",
},
{ id : 8,
  titleProf: "Marie-Pierre Langlamet",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Harpe",
},
{ id : 9,
  titleProf: "Denis Servin",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Cello",
},
{ id : 10,
  titleProf: "Pierre Génisson",
  textProf:
  ".",
  imageProf : " ",
  instrumentCategory: "Clarinet",
},
{ id : 11,
  titleProf: "Philippe Graffin",
  textProf:".",
  imageProf : " ",
  instrumentCategory: "Violon",
},
{ id : 12,
  titleProf: "Gérard Caussé",
  textProf:"Gérard Caussé has been exploring all the territories of the viola’s voice for many years: as a soloist, chamber musician, conductor and teacher, he has recently developed a passion, with Laurent Terzieff, for the dialogue between poetry and music, as evidenced by the Erato recording of Bach’s Cello Suites, transcribed for the viola, interwoven with Rilke’s poetry.",
  imageProf : " ",
  instrumentCategory: "Violon",
},
{ id : 13,
  titleProf: "Jean-Frédéric Neuburger",
  textProf:"Born in Paris in 1986, Jean-Frédéric Neuburger received an intense and varied musical education in piano, composition and organ before joining the Conservatoire National Supérieur de Musique et de Danse de Paris at the age of thirteen. On graduating from the CNSM with Five ‘Premier Prix’ he went on to study composition with Michael Jarrell and Pascal Dusapin in Geneva.He has, since then established himself as one of the most gifted musicians of his generation, both as a composer and an interpreter known for the extreme variety of his repertoire.",
  imageProf : " ",
  instrumentCategory: "Piano",
},
{ id : 14,
  titleProf: "Dmitri Alexeev",
  textProf:"Russian pianist Dmitri Alexeev is one of the world’s most highly regarded artists. His critically acclaimed recitals on the world’s leading concert stages and concerto appearances with the most prestigious orchestras have secured his position as one of “the most remarkable pianists of the day” (Daily Telegraph)",
  imageProf : " ",
  instrumentCategory: "Piano",
},
{ id : 15,
  titleProf: "Nelson Goerner",
  textProf:"Nelson Goerner is one of today’s greatest classical pianists. He is heralded for his performances of the highest art and poetry, while at the same time possessing exhilarating and masterful conviction.",
  imageProf : " ",
  instrumentCategory: "Piano",
},
{ id : 16,
  titleProf: "Ning Feng",
  textProf:"Ning Feng is recognised internationally as an artist of great lyricism, innate musicality and stunning virtuosity. He performs across the globe with major orchestras and conductors, and in recital and chamber concerts in some of the most important international series and festivals.",
  imageProf : " ",
  instrumentCategory: "Violon",
},
{ id : 17,
  titleProf: "Tedi Papavram",
  textProf:"Professor at the Haute École de Musique in Geneva. He won several important international prizes in the 1990s.",
  imageProf : " ",
  instrumentCategory: "Violon",
},
{ id : 18,
  titleProf: "Sivia Careddu",
  textProf:"Professor at the École Normale de Musique Alfred Cortot in Paris. Professor at the Scuola di Musica di Fiesole, in Italy.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Silvia-Careddu-Flute-Masterclass-1.jpg",
  instrumentCategory: "Flute",
},
{ id : 19,
  titleProf: "Sharon Kam",
  textProf:"One of the world's leading clarinet soloists, she has worked with renowned orchestras.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Sharon-Kam-Clarinet-Masterclass-1.jpg",
  instrumentCategory: "Flute",
},
{ id : 20,
  titleProf: "Mia Cooper",
  textProf:"Professor of Violin at the Royal Irish Academy of Music. She was principal first violin of the Royal Philharmonic Orchestra for five years.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Mia-Cooper-Violin-Masterclass-1.jpg",
  instrumentCategory: "Flute",
},
{ id : 21,
  titleProf: "Mary Brennan",
  textProf:"Professor at Vocal Studies Faculty of the Royal Irish Academy of Music since 2007",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Mary-Brennan-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voice",
},
{ id : 22,
  titleProf: "Jacques Mauger",
  textProf:"Professor at the Haute école de musique de Genève. International soloist and concert artist.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jacques-Mauger-Trombone-Masterclass-1.jpg",
  instrumentCategory: "Trombone",
},
{ id : 23,
  titleProf: "Isabel Charisius",
  textProf:"Member of the Alban Berg Quartet from 2005 to 2008. Teacher at the European Centre for Chamber Music - ProQuartet.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Isabel-Charisius-Chamber-music-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 24,
  titleProf: "Dénes Várjon",
  textProf:"He won first prize at the Piano Competition of Hungarian Radio, at the Leó Weiner Chamber Music Competition and at the Géza Anda Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Denes-Varjon-Piano-Masterclass-1.jpg-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 25,
  titleProf: "Claire-Marie Le Guay",
  textProf:"Professor at the CNSMD of Paris.First prize winner at ARD Competition in Munich (1994).",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Claire-Marie-Le-Guay-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 26,
  titleProf: "Céline Moinet",
  textProf:"Professor at the Hochschule für Musik Carl-Maria von Weber in Dresden.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Celine-Moinet-Oboe-Masterclass-1.jpg",
  instrumentCategory: "Hautbois",
},
{ id : 27,
  titleProf: "Céline Moinet",
  textProf:"Professor of violin at New England Conservatory in Boston. At the age of 20, she won the Paganini Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Miriam-Fried-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 28,
  titleProf: "Miriam Fried",
  textProf:"Professor of violin at New England Conservatory in Boston. At the age of 20, she won the Paganini Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Miriam-Fried-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 29,
  titleProf: "François Le Roux",
  textProf:"Former professor at the CNSMD of Paris, then at the École Normale de Musique Alfred Cortot of Paris.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Francois-Le-Roux-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix",
},
{ id : 30,
  titleProf: "Jens Peter Maintz",
  textProf:"Professor at the Berlin University of the Arts. He formed the cello duo « Cello Duello » with Wolfgang Emanuel Schmidt.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jens-Peter-Maintz-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 31,
  titleProf: "Boris Garlitsky",
  textProf:"Professor at the Berlin University of the Arts. He formed the cello duo « Cello Duello » with Wolfgang Emanuel Schmidt.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Boris-Garlitsky-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 32,
  titleProf: "Tatiana Samouil",
  textProf:"Professor at the Royal Conservatory of Brussels and at the Superior Center of Arts Musikene.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Tatiana-Samouil-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 33,
  titleProf: "Till Fellner",
  textProf:"Professor at the Zurich Hochschule der Künste. Jury president at the Ferruccio Busoni International Piano Competition in 2019.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Till-Fellner-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 34,
  titleProf: "Michel Dalberto",
  textProf:"Professor at the CNSMD of Paris. From 1991 to 2009, he chaired the jury of the Clara Haskil Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Michel-Dalberto-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 35,
  titleProf: "Anne Gastinel",
  textProf:"Professor at the CNSMD of Lyon. Anne Gastinel won numerous prizes in major international competitions (Scheveningen, Prague, Rostropovitch).",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Anne-Gastinel-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 36,
  titleProf: "Svetlana Makarova",
  textProf:"Professor at the Haute Ecole de Musique in Lausanne in Switzerland.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Svetlana-Makarova-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 37,
  titleProf: "Pavel Vernikov",
  textProf:"Professor of the highly esteemed Konservatorium Wien University. Professor at the Haute Ecole de Musique in Lausanne.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Pavel-Vernikov-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 38,
  titleProf: "Mihaela Martin",
  textProf:"Professor at the University of Music in Cologne. Professor at the Haute Ecole de Musique in Geneva.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Mihaela-Martin-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 39,
  titleProf: "Jacques Rouvier",
  textProf:"Professor at the CNSMD in Paris and at the Berlin University of the Arts.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jacques-Rouvier-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 40,
  titleProf: "Thérèse Fahy",
  textProf:"Professor at the Royal Irish Academy of Music.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Therese-Fahy-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 41,
  titleProf: "Frans Helmerson",
  textProf:"Professor at the Musikhochschule in Cologne and at the Escuela Superior de Musica Reina Sofia in Madrid.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Franz-Helmerson-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 42,
  titleProf: "Stephen Kovacevich",
  textProf:"He has conducted the Chamber Orchestra of Europe.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Stephen-Kovacevich-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 43,
  titleProf: "Sung-Won Yang",
  textProf:"Professor at the School of Music Yonsei University in Seoul and visiting professor at the Royal Academy London.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Sung-won-Yang-Cello-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 44,
  titleProf: "Philippe Bernold",
  textProf:"Professor of flute and chamber music at the CNSMD of Paris.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Philippe-Bernold-Flute-Masterclass-1.jpg",
  instrumentCategory: "Flute",
},
{ id : 45,
  titleProf: "Olivier Gardon",
  textProf:"Professor at the Hochschule in Hanover, at the Schola Cantorum in Paris. He was the artistic director of the International Summer Academy in Nice.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Philippe-Bernold-Flute-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 45,
  titleProf: "Peter Bruns",
  textProf:"Professor at the Mendelssohn Hochschule Leipzig.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Peter-Bruns-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle ",
},
{ id : 46,
  titleProf: "Olivier Charlier",
  textProf:"Revealed by the Long-Thibaud Foundation competition. Winner of the Young Concert Artists International Audition in 1989.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Olivier-Charlier-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
},
{ id : 47,
  titleProf: "Michel Béroff",
  textProf:"Professor at the CNSM of Paris. From 1991 to 2009, he chaired the jury of the Clara Haskil Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Michel-Beroff-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano ",
},
{ id : 48,
  titleProf: "Nathan Braude",
  textProf:"Professor at the Royal College of Music of London. 1st viola of the Gurzenich Orchester Cologne since 2016.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Nathan-Braude-Viola-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
},
{ id : 49,
  titleProf: "Margreet Honig",
  textProf:"She has gained international recognition for being a vocal coach to many singers who have developed advanced careers in professional singing.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Margreet-Honig-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix ",
},
{ id : 50,
  titleProf: "Marie-Josèphe Jude",
  textProf:"Professor at the CNSMD of Paris. In October 2017, she was appointed President of the Nice International Summer Academy.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Marie-Josephe-Jude-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano ",
},
{ id : 51,
  titleProf: "Maarten Koningsbergerr",
  textProf:"He has taught singing at the Amsterdam Conservatory of Music, the CNSMD of Paris and the Centre de Musique Baroque de Versailles.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Marteen-Koningsberger-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix ",
},
{ id : 52,
  titleProf: "Kim Kashkashian",
  textProf:"She coaches chamber music and viola at New England Conservatory of Music. She won a Grammy Award for her recording of Ligeti and Kurtag solo viola works in 2013.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Kim-Kashkashian-Viola-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
},
{ id : 53,
  titleProf: "Kim Kashkashian",
  textProf:"He is Artistic Director of the Kaposvár International Chamber Music Festival.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Kristof-Barati-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
},
{ id : 54,
  titleProf: "Kristof Barati",
  textProf:"He is Artistic Director of the Kaposvár International Chamber Music Festival.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Kristof-Barati-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
},
{ id : 55,
  titleProf: "Lars Anders Tomter",
  textProf:"Professor at the State Academy in Oslo. Professor at the Royal Danish Music Academy in Copenhagen.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Lars-Anders-Tomter-Viola-Masterclass-1.jpg",
  instrumentCategory: "Violon ",
},
{ id : 56,
  titleProf: "Jean-Paul Fouchécourt",
  textProf:"He has been directing the destiny of the Studio de l'Opéra de Lyon (SOL).",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jean-Paul-Fouchecourt-Voice-Masterclass-1.jpg",
  instrumentCategory: "Voix",
},
{ id : 57,
  titleProf: "Jean-François Heisser",
  textProf:"From 1991 to 2016, he was a professor at the CNSMD of Paris. He is the President of the Maurice Ravel International Academy.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Jean-Francois-Heisser-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 58,
  titleProf: "Günter Pichler",
  textProf:"Founder of the Alban Berg Quartett. Teacher at the European Centre for Chamber Music - ProQuartet.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gunter-Pichler-Chamber-music-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 59,
  titleProf: "Günter Pichler",
  textProf:"Professor at the Royal Academy of Music in London. He offers masterclasses at Curtis, Peabody, Yale, Cleveland, Oberlin, Manhattan School, San Francisco, and Juilliard School and other.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gyorgy-Pauk-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 60,
  titleProf: "Hugh Tinney",
  textProf:"Professor at the Royal Irish Academy of Music in Dublin.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Hugh-Tinney-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 61,
  titleProf: "Finghin Collins",
  textProf:"He will chair the jury of the Clara Haskil Competition in 2023 and 2025. He was a member of the jury of the Clara Haskil Competition in 2021 and the Dublin International Piano Competition in 2022.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Finghin-Collins-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 62,
  titleProf: "Gerard Poulet",
  textProf:"Former professor at the CNSMD of Paris, the CNR of Paris, and the Ecole Normale de Musique of Paris. Professor at the Showa University of Music in Japan since 2010.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Gerard-Poulet-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 63,
  titleProf: "Dmitry Sitkovetsky",
  textProf:"International soloist and conductor.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2022/12/Jpeg-300x17068-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 64,
  titleProf: "Clive Greensmith",
  textProf:"Professor at Colburn School. Member of the world-renowned Tokyo String Quartet and Montrose Trio.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Clive-Greensmith-Cello-Masterclass-1.jpg",
  instrumentCategory: "Musique de chambre",
},
{ id : 65,
  titleProf: "Davide Formisano",
  textProf:"Professor at Musikhochschule in Stuttgart, principal flutist at the Scala.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Davide-Formisano-Flute-Masterclass-1.jpg",
  instrumentCategory: "Flute",
},
{ id : 66,
  titleProf: "Denis Pascal",
  textProf:"Professor at the CNSMD of Paris.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Denis-Pascal-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 67,
  titleProf: "Chu Yi-Bing",
  textProf:"Former professor at the Beijing Conservatory. He founded the China Philarmonic Cellists and the SuperCello festival.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Chu-Yi-bing-Cello-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 68,
  titleProf: "Antti Siirala",
  textProf:"Professor at the Hochschule für Musik und Theater in Munich.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Antti-Siirala-Piano-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 69,
  titleProf: "Augustin Dumay",
  textProf:"Professor in Residence at the Chapelle Musicale Reine Elisabeth.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Augustin-Dumay-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 70,
  titleProf: "Barnabás Kelemen",
  textProf:"Professor at Budapest’s Liszt Academy and the University of Cologne. Winner of numerous international awards. Member of the Kelemen Quartet and renowned violinist.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Barnabas-Kelemen-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 71,
  titleProf: "Alissa Margulis",
  textProf:"International soloist and professor at Folkwang University, Germany.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Alissa-Margulis-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 72,
  titleProf: "Antoine Palloc",
  textProf:"Pianist and singing teacher.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Antoine-Palloc-Voice-Masterclass-1.jpg",
  instrumentCategory: "Piano, voix",
},
{ id : 73,
  titleProf: "Aleksandar Madžar",
  textProf:"Professor at Hochschule für Musik und Theater in Hamburg.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Aleksandar-Madzar-Piano-Masterclass-1.jpg",
  instrumentCategory: "Piano",
},
{ id : 74,
  titleProf: "Alexander Chaushian",
  textProf:"Professor at the Royal College of Music of London. He is a laureate prize winner of many international competitions, including International Tchaikovsky Competition.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Aleksandar-Madzar-Piano-Masterclass-1.jpg",
  instrumentCategory: "Violoncelle",
},
{ id : 75,
  titleProf: "Martin Beaver",
  textProf:"Professor of Violin and Chamber Music at the Colburn Conservatory of Music and Colburn Music Academy in Los Angeles. 1st violin of the legendary Tokyo string quartet.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Martin-Beaver-Violin-Masterclass-1.jpg",
  instrumentCategory: "Violon",
},
{ id : 76,
  titleProf: "Alexei Ogrintchouk",
  textProf:"Professor at the Haute Ecole de Musique de Genève and guest professor at the Royal Conservatory in The Hague, Netherlands.",
  imageProf : "https://www.salineacademy.com/wp-content/uploads/2023/06/Alexei-Ogrintchouk-Oboe-Masterclass-1.jpg",
  instrumentCategory: "Hautbois",
},
];
